global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    static_configs:
      # Docker-for-Mac can reach the host via host.docker.internal
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus
